echo 138 > /sys/class/gpio/export
echo 137 > /sys/class/gpio/export
echo 136 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio138/direction
echo out > /sys/class/gpio/gpio137/direction
echo out > /sys/class/gpio/gpio136/direction
open /sys/class/gpio/gpio138/value > 0
open /sys/class/gpio/gpio137/value > 1
open /sys/class/gpio/gpio136/value > 2
echo 1 > #0
echo 1 > #1
echo 1 > #2
