echo 161 > /sys/class/gpio/export
echo 158 > /sys/class/gpio/export
echo 156 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio161/direction
echo out > /sys/class/gpio/gpio158/direction
echo out > /sys/class/gpio/gpio156/direction
open /sys/class/gpio/gpio161/value > 0
open /sys/class/gpio/gpio158/value > 1
open /sys/class/gpio/gpio156/value > 2
echo 1 > #0
echo 1 > #1
echo 1 > #2
